# Generated by Django 4.0.4 on 2022-05-08 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precios',
            old_name='precio de compra',
            new_name='precio_de_compra',
        ),
        migrations.RenameField(
            model_name='precios',
            old_name='precio de venta',
            new_name='precio_de_venta',
        ),
    ]
